Microsoft (R) Direct3D Shader Compiler 9.29.952.3111
Copyright (C) Microsoft Corporation 2002-2009. All rights reserved.

//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//   fxc /Tps_3_0 /Zi /EColorTexPS ColorTex.hlsl
//
//
// Parameters:
//
//   sampler2D gTex;
//   float4 kColor;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   kColor       c0       1
//   gTex         s0       1
//

    ps_3_0
    dcl_texcoord v0.xy  // iTex0<0,1>
    dcl_2d s0

#line 6 "D:\code\Dissector\DissectorDX9\TestHLSL\ColorTex.hlsl"
    texld r0, v0, s0
    mul oC0, r0, c0  // ::ColorTexPS<0,1,2,3>

// approximately 2 instruction slots used (1 texture, 1 arithmetic)
