Microsoft (R) Direct3D Shader Compiler 9.29.952.3111
Copyright (C) Microsoft Corporation 2002-2009. All rights reserved.

//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//   fxc /Zi /Tps_3_0 /EComplicatedPS Complicated.hlsl
//
//
// Parameters:
//
//   sampler2D gShadow;
//   sampler2D gTex;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   gTex         s0       1
//   gShadow      s1       1
//

    ps_3_0
    dcl_texcoord v0.xy  // iTex0<0,1>
    dcl_2d s0
    dcl_2d s1

#line 9 "D:\code\Dissector\DissectorDX9\TestHLSL\Complicated.hlsl"
    texld r0, v0, s0  // ::val1<0,1,2,3>
    texld r1, v0, s1  // ::val2<0,1,2,3>

#line 4 "Common.hlsl"
    add r2, r0, r1  // ::rvalue<0,1,2,3>
    mul r2, r0, r2

#line 12 "D:\code\Dissector\DissectorDX9\TestHLSL\Complicated.hlsl"
    mad r0, r2, r1, r0
    add oC0, r1, r0  // ::ComplicatedPS<0,1,2,3>

// approximately 6 instruction slots used (2 texture, 4 arithmetic)
