Microsoft (R) Direct3D Shader Compiler 9.29.952.3111
Copyright (C) Microsoft Corporation 2002-2009. All rights reserved.

//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//   fxc /Zi /Tps_3_0 /EIncludeTestPS IncludeTest.hlsl
//
//
// Parameters:
//
//   float4 kBlend;
//   float4 kColor;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   kColor       c0       1
//   kBlend       c1       1
//

    ps_3_0

#line 4 "Common.hlsl"
    mov r0, c0  // ::kColor<0,1,2,3>
    add r0, r0, c1  // ::rvalue<0,1,2,3>
    mul r0, r0, c0
    mul r0, r0, c1  // ::rvalue<0,1,2,3>

#line 8 "D:\code\Dissector\DissectorDX9\TestHLSL\IncludeTest.hlsl"
    mul oC0, r0, c0  // ::IncludeTestPS<0,1,2,3>

// approximately 5 instruction slots used
