Microsoft (R) Direct3D Shader Compiler 9.29.952.3111
Copyright (C) Microsoft Corporation 2002-2009. All rights reserved.

//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//   fxc /Tvs_3_0 /Zi /EPosVertexVS PosVertex.hlsl
//
    vs_3_0
    def c0, 1, 0, 0, 0
    dcl_position v0  // iVert<0,1>
    dcl_texcoord v1  // iVert<2,3>
    dcl_position o0
    dcl_texcoord o1.xy

#line 16 "D:\code\Dissector\DissectorDX9\PosVertex.hlsl"
    mad o0, v0.xyxx, c0.xxyy, c0.yyyx  // ::PosVertexVS<0,1,2,3>
    mov o1.xy, v1  // ::PosVertexVS<4,5>

// approximately 2 instruction slots used
