Microsoft (R) Direct3D Shader Compiler 9.29.952.3111
Copyright (C) Microsoft Corporation 2002-2009. All rights reserved.

//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//   fxc /Tps_3_0 /Zi /ESingleColorPS SingleColor.hlsl
//
//
// Parameters:
//
//   float4 kColor;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   kColor       c0       1
//

    ps_3_0

#line 5 "D:\code\Dissector\DissectorDX9\SingleColor.hlsl"
    mov oC0, c0  // ::SingleColorPS<0,1,2,3>

// approximately 1 instruction slot used
