Microsoft (R) Direct3D Shader Compiler 9.29.952.3111
Copyright (C) Microsoft Corporation 2002-2009. All rights reserved.

//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//   fxc /Tps_3_0 /Zi /ETripleColorPS TripleColor.hlsl
//
//
// Parameters:
//
//   float4 kBlah;
//   float4 kBlend;
//   float4 kColor;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   kColor       c0       1
//   kBlend       c1       1
//   kBlah        c2       1
//

    ps_3_0

#line 7 "D:\code\Dissector\DissectorDX9\TripleColor.hlsl"
    mov r0, c0  // ::kColor<0,1,2,3>
    mul r0, r0, c1
    mad oC0, r0, c2, c2  // ::TripleColorPS<0,1,2,3>

// approximately 3 instruction slots used
